on: [workflow_dispatch]

jobs:
  deployment:
    runs-on: ubuntu-latest
    name: Deploy new milestones from Camunda Web Modeler
    permissions: write-all
    steps:
      - name: Sync
        id: sync
        uses: berndruecker/github-action-sync-milestones@main
        env:
          ZEEBE_ADDRESS: ${{ secrets.CAMUNDA_ZEEBE_ADDRESSS }}
          ZEEBE_CLIENT_ID: ${{ secrets.CAMUNDA_CLIENT_ID }}
          ZEEBE_CLIENT_SECRET: ${{ secrets.CAMUNDA_CLIENT_SECRET }}
          CAMUNDA_OAUTH_URL: 'https://login.cloud.camunda.io/oauth/token'
        with:
          github-token:  ${{ secrets.GITHUB_TOKEN }}
          webmodeler-client-id:  ${{ secrets.CAMUNDA_WEBMODELER_CLIENT_ID }}
          webmodeler-client-secret:  ${{ secrets.CAMUNDA_WEBMODELER_CLIENT_SECRET }}
          camunda-client-id:  ${{ secrets.CAMUNDA_CLIENT_ID }}
          camunda-client-secret: ${{ secrets.CAMUNDA_CLIENT_SECRET }}
          camunda-zeebe-address: ${{ secrets.CAMUNDA_ZEEBE_ADDRESSS }}
