on: [workflow_dispatch]

jobs:
  sync_job:
    runs-on: ubuntu-latest
    name: lalala
    steps:
      - name: Sync
        id: sync
        uses: berndruecker/github-action-sync-milestones@main
        with:
          who-to-greet: 'Mona the Octocat'
          github-token:  ${{ secrets.GITHUB_TOKEN }}
          webmodeler-client-id:  ${{ secrets.CAMUNDA_WEBMODELER_CLIENT_ID }}
          webmodeler-client-secret:  ${{ secrets.CAMUNDA_WEBMODELER_CLIENT_SECRETS }}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
